### PR TITLE
Text Tagger

### LINKED ISSUE #297: Tagger: Text Tagger
Part of #267: Text Tagger

Add a skeleton Text Tagger page.

### PR DESCRIPTION
**Pull request by dwhieb**
**Related Issue:**

closes #297

**Description**

Adds a skeleton Text Tagger view.

### CODE REVIEW

**Comment by dwhieb** [comment]
[[app] skeleton Text Tagger](https://trello.com/c/QNXp4AJd/376-app-skeleton-text-tagger)

**Comment by vadekh** [comment]
@dwhieb If you dont mind I'm going to wait until some other PRs are closed and then review this and PR #304

**Comment by dwhieb** [comment]
Absolutely! That was kinda my plan actually haha. Thanks for all these reviews so far!

**Comment by dwhieb** [comment]
[[app] Text Tagger (revisions)](https://trello.com/c/OrA9lzd8/548-app-text-tagger-revisions)

**Comment by dwhieb** [comment]
@vadekh This PR is up to date with master now, ready for your review.

**Pull request merged**
