### PR TITLE
use real language data in tests

### LINKED ISSUE #299: use real language data
Use real language and text data for testing. Get data from Chitimacha and Nuuchahnulth.

### PR DESCRIPTION
**Pull request by dwhieb**
### Related Issue

closes #299

### Description

Replaces the test data with real data from the Nuuchahnulth and Chitimacha languages. It's always a good idea to test with realistic data!

**Languages**
- Nuuchahnulth (`cid` = `"1"`)
- Chitimacha (`cid` = `"2"`)

**Texts**
- How people saw a solar eclipse (Nuuchahnulth, cid = `"1"`, abbr = `"Eclipse"`)
- Feasts (Nuuchahnulth, cid = `"2"`, abbr = `"Feasts"`)
- How the Indian came (first telling) (Chitimacha, cid = `"3"`, abbr = `"A1"`)
- Trip to the end of the world (Chitimacha, cid = `"4"`, abbr = `"B1"`)

**Note:** The client IDs are strings, not integers. I used these numbers instead of a UUID (which is what the app actually uses) to make testing easier.

### CODE REVIEW

**Comment by dwhieb** [comment]
[[app] use real language data](https://trello.com/c/osXbBlZw/375-app-use-real-language-data)

**Comment by vadekh** [comment]
@dwhieb Looks good to me, should be all set after the previous PR is merged, and this is up to date with those changes.

**Comment by dwhieb** [comment]
[[app] use real language data in tests](https://trello.com/c/qetfT0rS/549-app-use-real-language-data-in-tests)

**Comment by dwhieb** [comment]
@vadekh I've got the repo set to auto-dismiss reviews if the PR is updated. (This keeps us from accidentally introducing breaking changes after a PR has been reviewed.) Any comments you made will still be visible though. I don't think that's what happened here, because there's typically a note that the review was dismissed, but just FYI.

**Comment by dwhieb** [comment]
Updated from `master`, all tests passing, skipping additional review.

**Comment by dwhieb** [comment]
[👨🏼‍💻 [app] update to DLx JS v0.4.0](https://trello.com/c/QqkhD1nx/613-%F0%9F%91%A8%F0%9F%8F%BC%F0%9F%92%BB-app-update-to-dlx-js-v040)

**Pull request merged**
