### PR TITLE
Fira Mono

### LINKED ISSUE #342: self-host Fira Mono font
Self-host the Fira Mono font.

### PR DESCRIPTION
**Pull request by dwhieb**
**Related Issue:**

closes #342

**Description of Changes**

Makes the Fira Mono font available to the app, for use in #343.

The failing tests should be fixed by #376 when it's merged.

### CODE REVIEW

**Review by vadekh — COMMENTED** [review]
I'll come back to this when #376 is merged in

**Comment by dwhieb** [comment]
@vadekh Just merged #376, ~~which amazingly didn't generate any merge conflicts for this PR~~. ~~It's ready for your review now.~~

Just saw you handled the merge from `main`, so maybe there were merge conflicts I just didn't see... lol. Thanks for tackling that!

Tests are failing still. I'll take a look and see if I fix them.

**Comment by vadekh** [comment]
> @vadekh Just merged #376, ~which amazingly didn't generate any merge conflicts for this PR~. It's ready for your review now.
> 
> Just saw you handled the merge from `main`, so maybe there were merge conflicts I just didn't see... lol. Thanks for tackling that!

There weren't any conflicts, but it does look like some tests are failing, bc storybook can't find one of the fonts. Or in might be Cypress, not sure.

**Comment by dwhieb** [comment]
@vadekh Just had to fix some filepaths in the `fonts.less` file. All tests are passing now, so I'll go ahead and merge this.

**Pull request merged**
