### PR TITLE
fix / improve link styles

### LINKED ISSUE #307: improvements to `.link` class
You can UTF8-encode reusable SVG icons, e.g.

```css
.svgbackground {
  background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><circle cx="300" cy="300" r="150" stroke-width="3" stroke="#f00" fill="#ff0" /></svg>');
}
```
---
Also use drop shadows on external links.

### LINKED ISSUE #336: external link styles are broken
image

### PR DESCRIPTION
**Pull request by dwhieb**
* Uses UTF-8 encoding for external link icon. (#307)
* Fixes display issue for external links. (#336)

### CODE REVIEW

**Review by vadekh — COMMENTED** [review]
Good news and bad news:

- This fixes the inline `(external link)` text displaying issue, and external links look good in the page bodies.
- However, the absolute positioning of the icon has messed up the `HelpMenu` links again.

**Comment by dwhieb** [comment]
🤬 lol

**Comment by vadekh** [comment]
@dwhieb the easiest solution might be to override the `position: absolute` in HelpMenu link styles.

**Comment by dwhieb** [comment]
> @dwhieb the easiest solution might be to override the `position: absolute` in HelpMenu link styles.

Tried this, didn't work. Came up with a convoluted alternative solution. Read your comment. Remembered that overriding `position: absolute` _did_ work previously and went "huh, why didn't it work this time?". Looked again, realized I did it wrong. Undid my convoluted changes. Applied the override. Problem solved.

Literally a one-line fix that took me an hour to get to 😑

**Review by vadekh — APPROVED** [review]
Yep looks good now! I have a feeling the icon positioning issue may pop up again in #297 so we should keep in mind the one-line fix.

**Pull request merged**
