### PR TITLE
Nav: expand/collapse

### LINKED ISSUE #125: Nav: make collapsible
The user should be able to collapse the main navigation menu.

- [x] HTML for menu icon
- [x] styling for open + desktop (icons + text)
- [x] clicking menu icon toggles nav (with transition)
  - [x] menu button toggles `aria-expanded` state
  - [x] ~~CSS transition~~ (really complicated to implement with `.visually-hidden`)
- [x] ~~when collapsed, focus/hover expands nav~~ (turned out to be poor UX)
- [x] styling for closed + desktop (icons only)
  - [x] don't use `hidden`, use `.visually-hidden` for text
- [x] styling for open + mobile (icons + text)
- [x] styling for closed + mobile (menu icon only)

### PR DESCRIPTION
**Pull request by dwhieb**
closes #125: make Nav collapsible

### CODE REVIEW

**Comment by dwhieb** [comment]
[👨🏼‍💻 [app] Nav: make collapsible](https://trello.com/c/rR1XCSIa/675-%F0%9F%91%A8%F0%9F%8F%BC%F0%9F%92%BB-app-nav-make-collapsible)

**Review by vadekh — DISMISSED** [review]
Looks good!

**Comment by dwhieb** [comment]
@vadekh I accidentally just dismissed your review while I was updating this branch from `master` haha. But something broke in the tests after I did anyway so I'll fix that soon and rerequest your review when I do.

**Review by vadekh — APPROVED** [review]
Noticed separately that the default backup setting is `never` as opposed to `daily`. I dont have a preference between the two, but wanted to be sure it was working as intended.

**Comment by dwhieb** [comment]
@vadekh Oh good catch! I'll open an issue for that. I definitely think the default should be daily. Thanks for the review!

**Pull request merged**
